### ISSUE TITLE
v2.11.0 showing High vulnerability CVE-2023-44487

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes-csi/livenessprobe#222]
Hello, our security tooling is showing the latest version has CVE-2023-44487. This requires upgrading Golang to a later patch version to pull in the latest net package.
![Screenshot 2023-10-27 at 9 23 50 AM](https://github.com/kubernetes-csi/livenessprobe/assets/4107699/87192329-a3be-4035-82de-c9245bd396fb)

**Comment by coltonfreeman26** [comment]
Good day all,
Figured I would comment here instead of opening a new issue. 
We are also using the 2.11.0 release and our scan tools (Anchore and Twistlock) have found multiple CVEs in regards to the golang version being used 1.20.5 (all of which will be resolved with 1.20.10)

[CVE-2023-29406](https://nvd.nist.gov/vuln/detail/CVE-2023-29406)
[CVE-2023-29409](https://nvd.nist.gov/vuln/detail/CVE-2023-29409)
[CVE-2023-39318](https://nvd.nist.gov/vuln/detail/CVE-2023-39318)
[CVE-2023-39319](https://nvd.nist.gov/vuln/detail/CVE-2023-39319)
[CVE-2023-39323](https://nvd.nist.gov/vuln/detail/CVE-2023-39323)
[CVE-2023-39325](https://nvd.nist.gov/vuln/detail/CVE-2023-39325)

Please let me k now if you have any questions.

**Comment by jsafrane** [comment]
This has been fixed in v2.12.0
